"""create applied_highlights table

Revision ID: 280844977d6d
Revises: e6804cc93521
Create Date: 2026-08-30 12:54:44.392934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280844977d6d'
down_revision: Union[str, Sequence[str], None] = 'e6804cc93521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applied_highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spreadsheet_id', sa.String(length=128), nullable=False),
    sa.Column('ranges', sa.JSON(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spreadsheet_id', name='uq_applied_highlights_user_spreadsheet')
    )
    op.create_index(op.f('ix_applied_highlights_spreadsheet_id'), 'applied_highlights', ['spreadsheet_id'], unique=False)
    op.create_index(op.f('ix_applied_highlights_user_id'), 'applied_highlights', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applied_highlights_user_id'), table_name='applied_highlights')
    op.drop_index(op.f('ix_applied_highlights_spreadsheet_id'), table_name='applied_highlights')
    op.drop_table('applied_highlights')
    # ### end Alembic commands ###
